package com.mybatis.model;

import java.util.Date;

public class Students {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.stud_id
     *
     * @mbggenerated
     */
    private Integer studId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.dob
     *
     * @mbggenerated
     */
    private Date dob;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.stud_id
     *
     * @return the value of students.stud_id
     *
     * @mbggenerated
     */
    public Integer getStudId() {
        return studId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.stud_id
     *
     * @param studId the value for students.stud_id
     *
     * @mbggenerated
     */
    public void setStudId(Integer studId) {
        this.studId = studId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.name
     *
     * @return the value of students.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.name
     *
     * @param name the value for students.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.email
     *
     * @return the value of students.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.email
     *
     * @param email the value for students.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.dob
     *
     * @return the value of students.dob
     *
     * @mbggenerated
     */
    public Date getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.dob
     *
     * @param dob the value for students.dob
     *
     * @mbggenerated
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }
}
